### ISSUE TITLE
Is it possible to programmaticaly change the curently displayed image (by pos)

### ISSUE THREAD

**Issue by nickstamp93** [stfalcon-studio/StfalconImageViewer#11]
The idea is to add a view overlay containing a horizontal thumbs list at the bottom of the screen. So when a user clicks a thumb from the list, the falcon image viewer updates the currently displayed image (maybe with a gesture-like animation as well).

Is this possible?
Maybe i can achieve it by updating the image list on the fly?

**Comment by Pomis** [comment]
Have you manage to achieve this functionality somehow?

**Comment by nickstamp93** [comment]
Unfortunately not! I had to implement my own Gallery solution.

**Comment by Pomis** [comment]
Okay, I managed to do it with reflection:

```
class GalleryOverlay @JvmOverloads constructor(
        context: Context,
        attrs: AttributeSet? = null,
        defStyleAttr: Int = 0,
        ...
) : ConstraintLayout(context, attrs, defStyleAttr) {
     var parentView: StfalconImageViewer<String>? = null

     fun setCurrentItem(position: Int) {
        val frame = StfalconImageViewer::class.java.getDeclaredField("dialog")
        frame.isAccessible = true
        val dialog = frame.get(parentView)
        val viewerViewField = dialog::class.java.getDeclaredField("viewerView")
        viewerViewField.isAccessible = true
        val viewerView = viewerViewField.get(dialog) as RelativeLayout
        val viewPager = viewerView.findViewById<ViewPager>(R.id.imagesPager)
        viewPager.setCurrentItem(position, true)
    }
}
```

**Comment by nickstamp93** [comment]
Since there is no active maintenance from the library creator, your solution seems to be the only way for now, even though reflection is used. Good job @Pomis it may help many coders in the future

**Comment by troy379** [comment]
Hey guys
Sorry for such an inconvenience - this was done by @ adrianhartanto004  in #26 and will be added soon in version `0.1.1`
