### ISSUE TITLE
Is this library dead?

### ISSUE THREAD

**Issue by DrPechkin** [stfalcon-studio/StfalconImageViewer#20]
Is this library dead?

**Comment by string-areeb** [comment]
Seems like it. Not updated for 6 months. Not accepting PRs. Only few commits of initial development.

**Comment by hakansuluoglu** [comment]
NEEEEEH

**Comment by string-areeb** [comment]
@hakansuluoglu I know, disappointing

**Comment by troy379** [comment]
Hi @DrPechkin @string-areeb @hakansuluoglu 
The project was temporarily frozen, but now I'm back to fix all of the problems, he-he.
The new version will be released soon, stay tuned 😉
