### ISSUE TITLE
Background color not showing when withTransitionFrom(null)

### ISSUE THREAD

**Issue by adrianhartanto004** [stfalcon-studio/StfalconImageViewer#27]
**Problem**
Background color is not showing when `withTransitionFrom(imageView)` is set to `withTransitionFrom(null)`
**To Reproduce**
1. Set the viewer background color `.withBackgroundColor(Color.BLACK)`
2. Set the viewer method `.withTransitionFrom(targetImageView)` to `.withTransitionFrom(null)`
3. Click on any images in that has been set with the viewer
4. See error that the background is not totally black

**Expected behavior**
Background color should be black.

![image](https://user-images.githubusercontent.com/50439894/69319820-87a89980-0c72-11ea-878c-d2fc8eca488c.png)

**Comment by florian-do** [comment]
Hello,

Event with withTransitionFrom(imageView) the background alpha is at 0 at first

**Comment by adrianhartanto004** [comment]
> Hello,
> 
> Event with withTransitionFrom(imageView) the background alpha is at 0 at first

Hi there,
The background of the viewer will be transparent when the withTransitionFrom(imageView) is null because of the alpha from the view_image_viewer.xml backgroundView is set to 0.
I tried by changing the alpha to 1 or deleting the alpha of the backgroundView. This made the background black again which is good.
