### ISSUE TITLE
dialog can not dismiss

### ISSUE THREAD

**Issue by iielse** [stfalcon-studio/StfalconImageViewer#5]
**To Reproduce**
1. I use this library on the chat page (recyclerView)
2. Click image into viewer 
3. New message coming to bring the picture out of the screen
4. Click the back button to exit

I try to track the source code
`TransitionImageAnimator` `handleCloseTransitionEnd`

`externalImage?.post { onTransitionEnd() }` 
This line of code didn't work

`internalImage.post { onTransitionEnd() }`
now,I temporarily used this line of code to solve this problem.

**Comment by troy379** [comment]
Hey @iielse 
It makes sense, thank you.
You'll find the fix in `0.1.1`
