### ISSUE TITLE
Can it be used with a recyclerView?

### ISSUE THREAD

**Issue by AlexandruDev** [stfalcon-studio/StfalconImageViewer#6]
I have a list of images loaded using **Glide** inside a `RecyclerView`.  I want that when a user clicks an image, to display it using StfalconImageViewer (like in grid demo). How can I achieve this?

A piece of the `RecyclerView`'s adapter:
```
 override fun onBindViewHolder(holder: ViewHolder, position: Int) {
        holder.carTitle.text = imageTitleList[position]
        GlideApp.with(context)
                .load(imageUrls[position])
                .placeholder(R.drawable.placeholder_glide)
                .override(300, 150)
                .into(holder.carImage)

        holder.carImage.setOnClickListener {
            StfalconImageViewer.Builder<Image>(context, imageUrls) view, image ->
               // I have no idea how to do this...
            }.show()
        }
    }
```

**Comment by Alecckie** [comment]
public void onBindViewHolder(@NonNull final MyViewHolder holder, final int position) 
{	
	_//My image grid_
	Picasso.get().load(URL_UploadPath+imageList.get(position).getResource_name()).into(holder.image_resource_imageview);
	
	_//Setting onclick listener to each image in the grid_
	holder.image_resource_imageview.setOnClickListener(new View.OnClickListener() { 
	@Override
	public void onClick(View view) {

		_// Inflate the layout for this_
		LayoutInflater inflater = LayoutInflater.from(mContext);
		final View frescoView = inflater.inflate(R.layout.activity_image_options, null); //Custom overlay with options such as delete or share

		_//Library definition 
		//mContext 		-> Context
		//imageList 	-> Your arraylist/list
		//Decode_images	-> This is my adapater - the pojo -It allows you to use the adapter and call any get method in it_ 
		new StfalconImageViewer.Builder<>(mContext, imageList, new ImageLoader<Decode_images >() {
			@Override
			public void loadImage(ImageView imageView, Decode_images image) {
				_//Usage with picasso... you can use glide too_
				Picasso.get().load(URL_UploadPath+image.getResource_name()).into(imageView);
			}
		})
		.withStartPosition(position)
		.withOverlayView(frescoView)
		.withImageChangeListener(new OnImageChangeListener() {
			@Override
			public void onImageChange(final int position) {
				_//Handle your clicks here_
			}
		})
		.show(true); _//With animation true or false_
	}
	});

}

**Comment by AlexandruDev** [comment]
Working great! Thank you @Alecckie :+1:

**Comment by softsan** [comment]
I am getting this error:
`java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.`

while using the viewer in RecyclerView -> OnBindViewHolder
