### ISSUE TITLE
somthing wrong with the jitpack or the package i don't know

### ISSUE THREAD

**Issue by stefanusayudha** [stfalcon-studio/StfalconImageViewer#87]
Could not HEAD 'https://jitpack.io/com/github/stfalcon/stfalcon-imageviewer/1.0.1/stfalcon-imageviewer-1.0.1.pom'. Received status code 521 from server: 
 
 it seems like the jitpack is down or something but this is the only package that is affected so far

**Comment by budo385** [comment]
same here

**Comment by budo385** [comment]
@stefanusayudha looks like it was a jitpack issue. Working now
