### ISSUE TITLE
Unresolved reference: StfalconImageViewer

### ISSUE THREAD

**Issue by softsan** [stfalcon-studio/StfalconImageViewer#88]
Trying to install this library in my project which is Kotlin base.
but while using this:
```
 StfalconImageViewer.Builder<Image>(context, images) { view, image ->
                    Picasso.get().load(image.url).into(view)
                }.show()
```

it shows  above `Unresolved reference: StfalconImageViewer`
I tried importing the  `import com.stfalcon.imageviewer.StfalconImageViewer` but it too show the same message.

in my build.gradle i tried with:

`implementation 'com.github.stfalcon:stfalcon-imageviewer:v1.0.1'`

and also this
`implementation 'com.github.stfalcon:stfalcon-imageviewer:1.0.1' `(removing 'v' from path)

but still it doesn't able to find the reference.

Any idea?

**Comment by softsan** [comment]
Even tried with new project but it doesn't able to find the reference.

**Comment by iqbalShafiq** [comment]
Try to add 

`maven { url "https://jitpack.io" }`

In your settings.gradle also.

**Comment by fukemy** [comment]
@softsan saying thanks is importain part of being good developer

**Comment by softsan** [comment]
@fukemy @iqbalShafiq i am so sorry for late reply but was busy with something else and didn't work on the project where i was trying to integrate this. Thank you very much for your reply and support unfortunately I didn't get time to implement it. Thanks and apologies for delay response.
