### ISSUE TITLE
Delete image with ImageViewer showing

### ISSUE THREAD

**Issue by Alecckie** [stfalcon-studio/StfalconImageViewer#9]
The documentation tells us to use **updateImages(images)**
However, I'm getting an error: _Cannot resolve method updateImages_

delete_image.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(final View view) {
                    //Confirm alert
                    AlertDialog alertDialog = new AlertDialog.Builder(mContext).create();
                    alertDialog.setMessage("Delete this image permanently?");

                    alertDialog.setButton(AlertDialog.BUTTON_POSITIVE, "Ok", new DialogInterface.OnClickListener() {
                        public void onClick(DialogInterface dialog, int which) {
                            //
                            initialize_delete_image();
                            updateImages(imageList);
                        }
                    });
                    alertDialog.setButton(AlertDialog.BUTTON_NEGATIVE, "Cancel", new DialogInterface.OnClickListener() {
                        @Override
                        public void onClick(DialogInterface dialogInterface, int i) {

                        }
                    });

                    alertDialog.show();
                }
            });

**Comment by troy379** [comment]
You're not calling the `updateImages()` method on the viewer, you're just trying to invoke it in your class and, of course, it cannot be resolved.

Take a closer look [here](https://github.com/stfalcon-studio/StfalconImageViewer/blob/bd34c353fbd385958af361f282b055c251a5ecf5/sample/src/main/java/com/stfalcon/sample/features/demo/styled/StylingDemoActivity.kt#L102) for usage sample.
